### ISSUE TITLE
Regarding code for pre-trained DRUNet weights 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [deepinv/deepinv#152]
Hey folks,

Can the training code used to generate the pre-trained weights of the DRUNet as discussed in the library be shared ?

**Comment by matthieutrs** [comment]
Hey @svvenkatakrishnan, sure, I can share these! I'll just try to merge #147 first.

**Comment by matthieutrs** [comment]
Hi @svvenkatakrishnan, the PR is not merged yet but it's working. In the mean time, you can find [here](https://gist.github.com/matthieutrs/75823661ba4bc12726adf8b91eec97ad) a preliminary version of the codes I've used to train DRUNets [[weights]](https://huggingface.co/deepinv/drunet/tree/main). This code is not super clean mainly due to the handling of multi-gpu in the physics class: we need to keep track of the (randomly generated) standard deviation in the physics and pass that to the network.  

My training script looks like this:
```bash
python train_drunet.py --grayscale=1 --gpu_num=4
```

Training dataset is the one available [there](https://github.com/samuro95/GSPnP) which we shall put of hugging face.
The weights I've uploaded were trained for approximatly ~400k steps with batch size 256 (requiring 4 gpus). We will release weights for the full 800k steps soon :) 

Let me know if you have any question!

**Comment by svvenkatakrishnan** [comment]
Thank you very much!
